// src/handlers/home.js — watersedge-phase2-snapshot
import { h } from '../utils.js';
import { dbFirst, loadSection, defaultContact, defaultServices, defaultTestimonials, defaultMenu } from '../db.js';
import { renderPage } from '../render/page.js';
import { renderMenuPreview } from '../render/menu_preview.js';

function chatInlineTag() {
  const js = "(function(){" +
    "if(window.__afoInlineChat){return;}window.__afoInlineChat=true;" +
    "var css='.afo-chat-panel{position:fixed;right:18px;bottom:92px;z-index:9999;width:min(390px,calc(100vw - 36px));height:560px;max-height:calc(100vh - 128px);display:none;flex-direction:column;overflow:hidden;border:1px solid rgba(20,17,13,.14);border-radius:26px;background:#fffdf7;box-shadow:0 24px 80px rgba(0,0,0,.28);font-family:Inter,system-ui,sans-serif;color:#14110d}.afo-chat-panel.open{display:flex}.afo-chat-head{padding:16px 18px;background:#14110d;color:#fff;display:flex;justify-content:space-between;gap:12px;align-items:center}.afo-chat-head strong{display:block;font-size:15px}.afo-chat-head span{display:block;font-size:12px;opacity:.75;margin-top:2px}.afo-chat-close{background:rgba(255,255,255,.12);border:1px solid rgba(255,255,255,.18);color:#fff;border-radius:999px;width:32px;height:32px;cursor:pointer}.afo-chat-log{flex:1;overflow:auto;padding:14px;display:flex;flex-direction:column;gap:10px;background:#fff8ee}.afo-msg{max-width:88%;border-radius:18px;padding:10px 12px;font-size:14px;line-height:1.42;white-space:pre-wrap}.afo-msg.bot{align-self:flex-start;background:#fff;border:1px solid rgba(20,17,13,.1)}.afo-msg.user{align-self:flex-end;background:#0b8f86;color:#fff}.afo-chat-suggestions{display:flex;gap:8px;overflow-x:auto;padding:10px 12px;border-top:1px solid rgba(20,17,13,.1);background:#fffdf7;scrollbar-width:none}.afo-chat-suggestions::-webkit-scrollbar{display:none}.afo-chip{white-space:nowrap;border:1px solid rgba(20,17,13,.14);border-radius:999px;background:#fff;padding:7px 10px;font-size:12px;font-weight:800;cursor:pointer;color:#14110d;flex-shrink:0}.afo-chip.invite{background:#14110d;color:#fff;border-color:#14110d}.afo-room-panel{background:#fff;border-top:1px solid rgba(20,17,13,.1);padding:12px;display:none;flex-direction:column;gap:8px}.afo-room-panel.visible{display:flex}.afo-room-label{font-size:12px;font-weight:800;color:#14110d}.afo-room-url{font-size:11px;color:#555;word-break:break-all;background:#fff8ee;border-radius:8px;padding:7px 9px;border:1px solid rgba(20,17,13,.1)}.afo-room-btns{display:flex;gap:8px;flex-wrap:wrap}.afo-room-copy,.afo-room-open{background:#14110d;color:#fff;border:0;border-radius:999px;padding:7px 12px;font-size:11px;font-weight:800;cursor:pointer;text-decoration:none}.afo-room-open{background:#0b8f86}.afo-chat-form{display:flex;gap:8px;padding:12px;background:#fffdf7;border-top:1px solid rgba(20,17,13,.1)}.afo-chat-form input{flex:1;border:1px solid rgba(20,17,13,.18);border-radius:999px;padding:11px 13px;font:14px Inter,system-ui,sans-serif;background:#fff;color:#14110d}.afo-chat-form button{border:0;border-radius:999px;background:#14110d;color:#fff;padding:0 14px;font-weight:900;cursor:pointer}.sticky-cta a{background:#0b8f86!important;color:#fff!important}@media(max-width:640px){.afo-chat-panel{right:10px;left:10px;bottom:84px;width:auto;height:540px;max-height:calc(100vh - 104px);border-radius:24px}}';" +
    "var style=document.createElement('style');style.textContent=css;document.head.appendChild(style);" +
    "var panel=document.createElement('div');panel.className='afo-chat-panel';panel.innerHTML='<div class=\"afo-chat-head\"><div><strong>Chat / Reserve</strong><span>Reservations, menu, private events, follow-up</span></div><button class=\"afo-chat-close\" aria-label=\"Close chat\">x</button></div><div class=\"afo-chat-log\"></div><div class=\"afo-chat-suggestions\"><button class=\"afo-chip invite\" id=\"afo-invite-btn\">Invite a Friend</button><button class=\"afo-chip\" data-q=\"Can I book a table for Friday night?\">Book a table</button><button class=\"afo-chip\" data-q=\"What seafood do you recommend?\">Seafood picks</button><button class=\"afo-chip\" data-q=\"What are good brunch options?\">Brunch</button><button class=\"afo-chip\" data-q=\"Tell me about private events.\">Private Event</button></div><div class=\"afo-room-panel\" id=\"afo-room-panel\"><div class=\"afo-room-label\">Planning room created. Copy this link and send it to your friend.</div><div class=\"afo-room-url\" id=\"afo-room-url\"></div><div class=\"afo-room-btns\"><button class=\"afo-room-copy\" id=\"afo-room-copy\" type=\"button\">Copy Invite Link</button><a class=\"afo-room-open\" id=\"afo-room-open\" target=\"_blank\" rel=\"noopener\">Open Room</a></div></div><form class=\"afo-chat-form\"><input autocomplete=\"off\" placeholder=\"Ask about reservations, menu, events...\"><button>Send</button></form>';document.body.appendChild(panel);" +
    "var launcher=document.querySelector('.sticky-cta a');if(!launcher){var wrap=document.createElement('div');wrap.className='sticky-cta';launcher=document.createElement('a');launcher.href='#';wrap.appendChild(launcher);document.body.appendChild(wrap);}launcher.textContent='Chat / Reserve';launcher.href='#chat-reserve';launcher.setAttribute('role','button');" +
    "var log=panel.querySelector('.afo-chat-log');var input=panel.querySelector('input');var form=panel.querySelector('form');var history=[];function add(role,text){var el=document.createElement('div');el.className='afo-msg '+(role==='user'?'user':'bot');el.textContent=text;log.appendChild(el);log.scrollTop=log.scrollHeight;}function openChat(){panel.classList.add('open');if(!log.childNodes.length){add('bot','Hi! I can help with reservations, menu questions, brunch, date night, seafood picks, private events, or invite a friend to plan together.');}setTimeout(function(){input.focus();},60);}function closeChat(){panel.classList.remove('open');}" +
    "async function send(text){text=String(text||'').trim();if(!text){return;}add('user',text);history.push({role:'user',content:text});input.value='';add('bot','Thinking...');var pending=log.lastChild;try{var r=await fetch('/api/chat',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({message:text,history:history})});var d=await r.json();pending.textContent=(d.reply||d.response||'Thanks, I received your message.')+(d.next?'\\n\\n'+d.next:'');history.push({role:'assistant',content:pending.textContent});}catch(e){pending.textContent='Sorry, chat is having trouble right now. Please try again or use the contact form.';}}" +
    "async function createRoom(){var roomPanel=document.getElementById('afo-room-panel');if(roomPanel.classList.contains('visible')){roomPanel.classList.remove('visible');return;}add('bot','Creating your planning room...');try{var r=await fetch('/api/chat/room/create',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({name:'Guest',intent:'restaurant planning room'})});var d=await r.json();if(d.ok&&d.share_url){document.getElementById('afo-room-url').textContent=d.share_url;document.getElementById('afo-room-open').href=d.share_url;roomPanel.classList.add('visible');add('bot','Planning room created! Copy the link and send it to your friend. You can both plan the reservation or menu together.');}else{add('bot','I could not create the room yet. Please try again.');}}catch(e){add('bot','Sorry, I could not create the room. Please try again.');}}" +
    "launcher.addEventListener('click',function(e){e.preventDefault();openChat();});panel.querySelector('.afo-chat-close').addEventListener('click',closeChat);form.addEventListener('submit',function(e){e.preventDefault();send(input.value);});panel.querySelectorAll('.afo-chip[data-q]').forEach(function(chip){chip.addEventListener('click',function(){send(chip.getAttribute('data-q'));});});document.getElementById('afo-invite-btn').addEventListener('click',function(e){e.preventDefault();createRoom();});document.getElementById('afo-room-copy').addEventListener('click',function(){var url=document.getElementById('afo-room-url').textContent;if(navigator.clipboard&&url){navigator.clipboard.writeText(url).then(function(){var b=document.getElementById('afo-room-copy');b.textContent='Copied!';setTimeout(function(){b.textContent='Copy Invite Link';},2000);});}});" +
    "})();";
  return '<script>' + js + '</scr' + 'ipt>';
}

function injectMenuPreview(html, menu) {
  const preview = renderMenuPreview(menu);
  if (!html || !preview || html.indexOf('menu-preview') !== -1) return html;
  const contactSection = '<section class="section" id="contact">';
  const oldContact = '<div class="section" id="contact">';
  if (html.indexOf(contactSection) !== -1) return html.replace(contactSection, preview + contactSection);
  if (html.indexOf(oldContact) !== -1) return html.replace(oldContact, preview + oldContact);
  if (html.indexOf('</main>') !== -1) return html.replace('</main>', preview + '</main>');
  if (html.indexOf('</body>') !== -1) return html.replace('</body>', preview + '</body>');
  return html + preview;
}

function injectChatWidget(html) {
  const tag = chatInlineTag();
  if (!html || html.indexOf('__afoInlineChat') !== -1) return html;
  if (html.indexOf('</body>') !== -1) return html.replace('</body>', tag + '</body>');
  return html + tag;
}

export async function handleHome(env, slug) {
  const menu = await loadSection(env, slug, 'menu', defaultMenu());
  const snap = await dbFirst(env, 'SELECT html FROM demo_snapshots WHERE slug=?', [slug]);
  if (snap?.html) return h(injectChatWidget(injectMenuPreview(snap.html, menu)));
  const contact      = await loadSection(env, slug, 'contact',      defaultContact());
  const services     = await loadSection(env, slug, 'services',     defaultServices());
  const testimonials = await loadSection(env, slug, 'testimonials', defaultTestimonials());
  return h(injectChatWidget(injectMenuPreview(renderPage(contact, services, testimonials, slug), menu)));
}
